Correct some typos
FreeProving/guidelines pull request #1
Opened 2020-05-27 10:10 UTC by stu204146-kiel

2020-05-27 11:10 UTC, just95 requested changes

2020-05-27 11:10 UTC, just95 commented on CONTRIBUTING.md
> +   This package is used by the Coq backend of the Free Compiler.
There are a lot of [discussions online](https://ell.stackexchange.com/questions/117383/what-is-the-correct-term-back-end-back-end-or-backend) whether "back end" or "backend" is the correct term. Personally, I've used the spelling with two words since that's what seems to be more widespread. For example, Wikipedia uses two words in their [article about compilers](https://en.wikipedia.org/wiki/Compiler#Back_end). However, I'd be fine spelling it "backend". This version would also be more consitent with the module names starting with `FreeC.Backend`. In this case we would have to update the remaining documentation of the Free Compiler, though.

2020-05-27 11:10 UTC, just95 commented on CONTRIBUTING.md
> +
This example was intensionally showing how redundant newlines should not be used but I forgot to make the not bold in the preceding paragraph. 

You probably had to make the changes below because your Markdown editor got confused by redundant newlines in the code block (at least mine does). However, GitHub can handle this the newlines but gets confused by your fix. Thus, the changes below should be undone.

2020-05-27 11:10 UTC, just95 commented on CONTRIBUTING.md
> +## Legal information
Please update the link in the Table of Contents accordingly.

2020-05-28 12:39 UTC, ichistmeinname approved these changes

2020-05-28 14:46 UTC, just95 requested changes

2020-05-28 14:46 UTC, just95 commented on CONTRIBUTING.md
> +   ​```bash
These are the changes I've meant in my [previous comment](https://github.com/FreeProving/guidelines/pull/1#discussion_r431032124) which should be undone. The closing ` ``` ` has no matching opening ` ```bash ` and is thus messing with GitHub's rendering of the code block.

````suggestion
   ```bash
````

2020-05-28 14:46 UTC, just95 commented on CONTRIBUTING.md
> +
Please avoid trailing whitespace. Also the blank line in line 583 is not needed.

2020-05-29 10:29 UTC, just95 approved these changes

2020-05-29 10:29 UTC, merged